<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Background (tezt.Tezt.Background)</title><link rel="stylesheet" href="../../../odoc.css"/><meta charset="utf-8"/><meta name="generator" content="odoc 1.5.2"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><script src="../../../highlight.pack.js"></script><script>hljs.initHighlightingOnLoad();</script></head><body><div class="content"><header><nav><a href="../index.html">Up</a> â€“ <a href="../../index.html">tezt</a> &#x00BB; <a href="../index.html">Tezt</a> &#x00BB; Background</nav><h1>Module <code>Tezt.Background</code></h1></header><aside><p>Promises to run in the background during tests.</p></aside><dl><dt class="spec value" id="val-register"><a href="#val-register" class="anchor"></a><code><span class="keyword">val</span> register : <span>unit Lwt.t</span> <span>&#45;&gt;</span> unit</code></dt><dd><p>Register a promise that will run in the background.</p><p>After a test runs, <code>Test.run</code> waits for all registered promises to finish.</p><p>If a registered promise raises an exception which is not <code>Lwt.Canceled</code>, the current test fails immediately, but <code>Test.run</code> still waits for other background promises to finish.</p><p>Make sure that the promise you register eventually resolves. If it doesn't, <code>stop</code> (and thus <code>Test.run</code>, which calls <code>stop</code>) will hang forever.</p><p>Calls to <code>register</code> when no test is running result in an error.</p></dd></dl><dl><dt class="spec value" id="val-start"><a href="#val-start" class="anchor"></a><code><span class="keyword">val</span> start : <span>(exn <span>&#45;&gt;</span> unit)</span> <span>&#45;&gt;</span> unit</code></dt><dd><p>Allow calls to <code>register</code> until <code>stop</code> is called.</p><p>If a promise that is later <code>register</code>ed is rejected by an exception which is not <code>Lwt.Canceled</code>, <code>start</code> calls its argument. This may occur several times, including during <code>stop</code>.</p><dl><dt>raises [Invalid_arg]</dt><dd><p>if calls to <code>register</code> are already allowed, i.e. if <code>start</code> has already been called without a corresponding <code>stop</code>.</p><p>Don't call this directly, it is called by <a href="../Test/index.html#val-run"><code>Test.run</code></a>.</p></dd></dl></dd></dl><dl><dt class="spec value" id="val-stop"><a href="#val-stop" class="anchor"></a><code><span class="keyword">val</span> stop : unit <span>&#45;&gt;</span> <span>unit Lwt.t</span></code></dt><dd><p>Let all <code>register</code>ed promises resolve, then stop allowing calls to <code>register</code>.</p><p>The promise returned by <code>stop</code> is never rejected except if you cancel it. If you do cancel it, you may have to call <code>stop</code> again though as it is not guaranteed that all background promises have also been canceled. In other words, canceling the promise returned by <code>stop</code> is probably a bad idea.</p><p>Calling <code>stop</code> when calls to <code>register</code> are not allowed has no effect, i.e. you can call <code>stop</code> even with no corresponding <code>start</code>.</p><p>Don't call this directly, it is called by <a href="../Test/index.html#val-run"><code>Test.run</code></a>.</p></dd></dl></div></body></html>